# Generated by Django 3.1.7 on 2021-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_larga',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cian_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
