# Generated by Django 3.1.7 on 2021-03-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion_corta',
            new_name='descripcion',
        ),
    ]
