# Generated by Django 3.1.7 on 2021-03-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210321_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
