# Generated by Django 3.1.7 on 2021-03-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_delete_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
