# Generated by Django 3.1.7 on 2021-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='pagado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
