# Generated by Django 3.1.7 on 2021-03-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20210321_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
    ]
