# Generated by Django 3.1.7 on 2021-03-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20210321_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cian_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cian_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='productos.producto'),
        ),
    ]
