# Generated by Django 3.1.7 on 2021-03-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20210322_0258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
    ]
