# Generated by Django 3.1.7 on 2021-03-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_auto_20210322_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cian_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.producto'),
        ),
    ]
